# Generated by Django 4.2.7 on 2023-12-01 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='List name', max_length=64)),
                ('description', models.CharField(help_text='List description', max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Last updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'updated_on', 'created_on'],
            },
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(auto_now_add=True, help_text='Due date')),
                ('name', models.CharField(help_text='Task name', max_length=64)),
                ('description', models.CharField(help_text='Task description', max_length=1000, null=True)),
                ('complete', models.BooleanField(default=False, help_text='Task is completed')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Last updated')),
                ('to_do_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDo.todolist')),
            ],
            options={
                'ordering': ['-complete', 'due_date', 'name'],
            },
        ),
    ]
