# Generated by Django 4.2.7 on 2023-12-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(help_text='Due date'),
        ),
    ]
