# Generated by Django 4.2.7 on 2023-12-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_alter_todoitem_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(help_text='Due date', null=True),
        ),
    ]
